"""Initial migration

Revision ID: 7583274ec8af
Revises: 
Create Date: 2025-02-19 23:15:34.836098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7583274ec8af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=280), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('service_preference', sa.String(length=120), nullable=True),
    sa.Column('area_interest', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
