"""User table addition

Revision ID: c286a0b8d9a6
Revises: 
Create Date: 2025-02-26 08:44:11.580213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c286a0b8d9a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=280), nullable=False),
    sa.Column('alias', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('idx_feedbacks_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index('idx_feedbacks_email', ['email'], unique=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('user_profiles')
    # ### end Alembic commands ###
