"""Staff Rating table addition

Revision ID: e18bfb9ebe16
Revises: c286a0b8d9a6
Create Date: 2025-03-08 10:26:39.208075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18bfb9ebe16'
down_revision = 'c286a0b8d9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rater_fk', sa.Integer(), nullable=False),
    sa.Column('rated_name', sa.String(length=110), nullable=False),
    sa.Column('rated_value', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_ratings')
    # ### end Alembic commands ###
